language: ruby
rvm:
  - 2.0.0
  - 2.1.2
before_install:
  - npm i -g jshint
  - jshint .
before_script:
  - psql -c 'create database discourse_test;' -U postgres
  - export DISCOURSE_HOSTNAME=www.example.com
  - export RUBY_GC_MALLOC_LIMIT=50000000
  - bundle exec rake db:migrate
bundler_args: --without development
script: 'bundle exec rspec && bundle exec rake plugin:spec && bundle exec rake qunit:test'
services:
  - redis-server
